### ISSUE TITLE
Minikube -- Too Many Redirects

### ISSUE THREAD

**Issue by devstein** [ibm-cloud-security/app-identity-and-access-adapter#43]
We are evaluating the `app-identity-and-access-adapter` and I am trying to deploy it to Minkube to test it out; however, I am getting an infinite redirect loop at the implicit `/oidc/callback` endpoint (`ERR_TOO_MANY_REDIRECTS`). I imagine the adapter is not intercepting the request correctly. Any idea what could be going wrong? Is this a configuration issue or an issue specific to Minikube? See my manifests below.

I am using the latest Minikube and Istio versions.

```yaml
---
apiVersion: "security.cloud.ibm.com/v1"
kind: OidcConfig
metadata:
  name: oidc-provider-config
spec:
  discoveryUrl: *******
  clientId: ********
  clientSecret: **********
---
apiVersion: "security.cloud.ibm.com/v1"
kind: Policy
metadata:
  name: samplepolicy
spec:
  targets:
    -
      serviceName: httpbin
      paths:
        - exact: /headers
          method: ALL
          policies:
            - policyType: oidc
              config: oidc-provider-config
              redirectUri: "https://github.com/ibm-cloud-security/app-identity-and-access-adapter"
```

```yaml
# httpbin for testing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```

**Comment by k3a** [comment]
Try to remove `redirectUri` from the `Policy`

**Comment by k3a** [comment]
Change `exact: /headers` to `prefix: /headers` (or don't specify exact/prefix uri rule).
I think the problem you are experiencing is that /headers/oidc/callback upon returning from the OpenID provider is not handled by this adabter unless the policy matches it too. I am not sure.

You should probably also remove `redirectUri` from the `Policy`.

**Comment by devstein** [comment]
@k3a I changes `exact: /headers` to `prefix: /headers` and removed the `redirectUri` but the behavior didn't change. I also tried to simplify it with a catch-all `prefix: /`. Here is the latest `Policy` config:

```yaml
kind: Policy
metadata:
  name: samplepolicy
spec:
  targets:
    -
      serviceName: httpbin
      paths:
        - prefix: /
          method: ALL
          policies:
            - policyType: oidc
              config: oidc-provider-config
```

**Comment by k3a** [comment]
That's odd. I basically use the following basic config which works for me. You can try to delete the browser cookie or use Private window / Firefox container to start from scratch. Also check the logs `kubectl logs -l app=appidentityandaccessadapter -n istio-system `.

```yaml
apiVersion: "security.cloud.ibm.com/v1"
kind:       OidcConfig
metadata:
  name:      oidc-provider-config
  namespace: default
spec:
  authMethod:   client_secret_basic
  discoveryUrl: https://DOMAIN/.well-known/openid-configuration
  clientId:     CLIENT_ID
  clientSecret: CLIENT_SECRET
---
apiVersion: "security.cloud.ibm.com/v1"
kind:       Policy
metadata:
  name:      httpbin
  namespace: default
spec:
  targets:
    - serviceName: httpbin
      paths:
        - method: ALL
          policies:
            - policyType: oidc
              config: oidc-provider-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        resources:
          limits:
            memory: "228Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  httpbin
spec:
  selector:
    app:  httpbin
  ports:
  - name:  http
    port:  80
    targetPort:  80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /httpbin
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    tls:
      mode: DISABLE

```
