### ISSUE TITLE
Okta Error

### ISSUE THREAD

**Issue by gcagrici** [ibm-cloud-security/app-identity-and-access-adapter#49]
Using the config below:

```
apiVersion: "security.cloud.ibm.com/v1"
kind: OidcConfig
metadata:
    name: my-oidc-provider-config
    namespace: kubeflow
spec:
    discoveryUrl: https://<org>.okta.com/oauth2/default/.well-known/openid-configuration
    clientId: <client_id>
    clientSecret: <client_secret>
```

Okta gives this error back:

```
Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.
```

Is this a know issue?

**Comment by devstein** [comment]
@gcagrici You need to specify `authMethod: client_secret_post` in your spec. I don't know if this is the expected behavior, but this will fix your issue. 

```
apiVersion: "security.cloud.ibm.com/v1"
kind: OidcConfig
metadata:
  name: app-id-oidc-config
spec:
  authMethod: client_secret_post
```
